# Generated by Django 5.1.7 on 2025-06-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pais',
        ),
    ]
