# Generated by Django 5.1.7 on 2025-06-25 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0003_pedido_bairro_pedido_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='tipo',
            new_name='tipo_impressao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='tipo',
            new_name='tipo_impressao',
        ),
    ]
