# Generated by Django 5.1.7 on 2025-06-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0004_rename_tipo_itemcarrinho_tipo_impressao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='tipo_impressao',
        ),
    ]
