# Generated by Django 5.1.7 on 2025-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0005_remove_itemcarrinho_tipo_impressao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='url_arquivo',
        ),
        migrations.AddField(
            model_name='produto',
            name='arquivo',
            field=models.FileField(default='arquivox', upload_to=''),
            preserve_default=False,
        ),
    ]
