# Generated by Django 5.1.7 on 2025-06-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0007_rename_arquivo_produto_url_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='endereco2',
            new_name='complemento',
        ),
    ]
