# Generated by Django 5.1.7 on 2025-06-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0009_alter_pedido_options_pedido_numero_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together=set(),
        ),
    ]
