# Generated by Django 5.1.7 on 2025-06-27 13:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0010_alter_pedido_options_alter_pedido_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criado']},
        ),
        migrations.AlterUniqueTogether(
            name='pedido',
            unique_together={('user', 'numero_pedido_usuario')},
        ),
    ]
