# Generated by Django 5.1.7 on 2025-07-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impressa_app', '0011_alter_pedido_options_alter_pedido_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(default='Em andamento', max_length=255),
        ),
    ]
